
services:
  company-service:
    build:
      context: '../company-service'
      dockerfile: Dockerfile
    container_name: company-service
    restart: unless-stopped
    ports:
      - "50051:50051"
    depends_on:
      - company-db
      - career-gateway-redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://company-db:5432/company_db
      SPRING_DATASOURCE_USERNAME: company_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      REDIS_HOST: career-gateway-redis
      REDIS_PORT: 6379
    networks:
      - backend-network

  company-db:
    image: postgres:latest
    container_name: company-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: company_db
      POSTGRES_USER: company_user
      POSTGRES_PASSWORD: password
    volumes:
      - company_postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network


  auth-service:
    build:
      context: '../auth-service'
      dockerfile: Dockerfile
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "50052:50052"
    depends_on:
      - auth-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth_db
      SPRING_DATASOURCE_USERNAME: auth_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
    networks:
      - backend-network


  auth-db:
    image: postgres:latest
    container_name: auth-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: password
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  career-gateway-redis:
    image: redis:latest
    container_name: career-gateway-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend-network
    command: ["redis-server", "--appendonly", "yes"]

networks:
  backend-network:
    driver: bridge

volumes:
  auth_postgres_data:
  company_postgres_data: